### PR TITLE
add knight cities application

### PR DESCRIPTION
**Pull request by jonleung**
Not the best application by any standards, but it was submitted!

### CODE REVIEW

**Comment by jonleung** [comment]
Assigning this back to myself until I fix the marcop tests.

**Comment by jonleung** [comment]
@msw @zachlatta, the tests seem to be marking things that are broken that are not broken.

There are the errors that I'm getting:

```
60:applications/knight_cities_app_fall_15.md '##  Location:' doesn't have a space between the # and the text of the header!
82:applications/knight_cities_app_fall_15.md '##  Contact Details:' doesn't have a space between the # and the text of the header!
33:applications/knight_cities_app_fall_15.md is over 80 chars!
39:applications/knight_cities_app_fall_15.md is over 80 chars!
40:applications/knight_cities_app_fall_15.md is over 80 chars!
51:applications/knight_cities_app_fall_15.md is over 80 chars!
```

This is the file that is supposedly broken but if you look at the errors and compare the files, this is not the case:

https://github.com/hackedu/meta/pull/253/files#diff-098b94b799bdad2d770c43117012c133R60

I filed the issue /hackedu/markcop#27 in response.

**Comment by MaxWofford** [comment]
You can find the commit to remote unicode characters here: https://github.com/hackedu/meta/commit/bfd5c70504228e1526980e5c3b62e86a26847247

**Comment by zachlatta** [comment]
Make sure to mention that this closes #243!

**Comment by jonleung** [comment]
@zachlatta @MaxWofford just a reminder to move this to "This week" for me in the future

**Comment by zachlatta** [comment]
I am going to steal this issue from you, @jonleung.

**Comment by MaxWofford** [comment]
bro my god that gif just won all of github

**Pull request closed without merging**
