### PR TITLE
Simplify our vision, mission, and values.

### PR DESCRIPTION
**Pull request by zachlatta**
I reworked our values and mission documents to keep it super brief and use the latest version of our vision and mission (I want to iterate on these down the line, pulled these from our most recent grant proposal).

This PR is also lacking descriptions for the values and what they actually mean, but I think it's a step in the right direction towards having a concrete document for this stuff.

Would love to hear @JacobEdelman, @MaxWofford, @gemmabusoni, @benzweig, and @jonleung's thoughts on this.

### CODE REVIEW

**Comment by JacobEdelman** [comment]
"self-confidence, social responsibility, inclusivity, collaboration, and agency." feels a bit like unnecessary listing.
The vision seems a tad too general.

**Comment by zachlatta** [comment]
>  "self-confidence, social responsibility, inclusivity, collaboration, and agency." feels a bit like unnecessary listing.

Yeah, it's definitely pretty fuzzy. Copied from a grant proposal we wrote where they want to hear words like these (and while we definitely still care about all of them, we might articulate them differently elsewhere, like in this PR).

> The vision seems a tad too general.

Agreed—it can definitely be refined.

What if we went ahead and merged this, then iterated on it later?

**Comment by JacobEdelman** [comment]
That seems okay to me.

**Comment by zachlatta** [comment]
@jonleung—thoughts?

**Comment by zachlatta** [comment]
Pinging @jonleung

**Comment by zachlatta** [comment]
Merging due to lack of response.

**Pull request merged**
