### PR TITLE
15-06-19_andrea_max_projects_curriculum.md in meetings 

### PR DESCRIPTION
**Pull request by MaxWofford**

### CODE REVIEW

**Comment by MaxWofford** [comment]
@zachlatta

**Comment by zachlatta** [comment]
Can you rename the file to follow the filename format of the other files in that directory?

`YY-MM-DD_name_of_meeting.md`

**Comment by MaxWofford** [comment]
Should be ready @zachlatta

**Comment by MaxWofford** [comment]
Thanks @zachlatta!

**Pull request merged**
