### PR TITLE
Form 1023

### PR DESCRIPTION
**Pull request by zachlatta**
Our 501(c)(3) application.

### CODE REVIEW

**Comment by tylermenezes** [comment]
Here's a sample one where I filled out a lot of the obvious things and annotated some of the major things you guys need to do: https://www.dropbox.com/s/xktll2klutea6vd/form_1023.pdf?dl=0

**Comment by zachlatta** [comment]
Awesome, thank you so much Tyler. You're the best.

**Comment by MaxWofford** [comment]
@zachlatta What should we do to close the PR?

**Comment by MaxWofford** [comment]
Closing for now due to lack of progress.

**Pull request closed without merging**
