### PR TITLE
Add today's retrospective notes

### PR DESCRIPTION
**Pull request by zachlatta**

### CODE REVIEW

**Comment by MaxWofford** [comment]
@zachlatta Failed tests in `GOALS.md`.

**Comment by jonleung** [comment]
@zachlatta, I assigned you to fix the failing checks.

**Comment by zachlatta** [comment]
So there was a bug in Markcop that was causing that failure. I've submitted hackedu/markcop#20 that fixes the bug. Once that's merged we should be able to rerun this PR's tests and it should be good to go (the tests passed locally).

**Comment by MaxWofford** [comment]
@zachlatta: on mobile right now. Would you please re run the tests?

**Comment by zachlatta** [comment]
Now passing!

**Comment by jonleung** [comment]
@zachlatta are these notes supposed to be linked from an index or a `README.md` from somewhere or was that changed?

**Comment by zachlatta** [comment]
I don't remember us agreeing on anything like that?

**Comment by jonleung** [comment]
Ah @zachlatta, I guess we only did that [in this repo](https://github.com/hackedu/hackedu/tree/master/meta/labs):

image

The branch is out of date, happy to merge when it is up to date again.

**Pull request closed without merging**
