### PR TITLE
Add list capital letter rule

### PR DESCRIPTION
**Pull request by paked**
I'd like to propose imposing a "All list items should start with a capital letter rule".

Currently throughout the repository we have a few people using different styles (@jonleung uses both! I use upper case, @Bogidon uses both). I personally find that upper case looks neater, but that may be bias...

Anyway, discuss.

cc: @zachlatta @MaxWofford

### CODE REVIEW

**Comment by zachlatta** [comment]
I'm down for this!

**Comment by MaxWofford** [comment]
This is good. I've been using uppercase.

**Comment by zachlatta** [comment]
@MaxWofford can you take point on fixing violations of this?

**Comment by MaxWofford** [comment]
@zachlatta Sounds good.

**Pull request merged**
